UCBG-474: Import permissions on initial install.

diff --git a/scripts/csops/csi b/scripts/csops/csi
--- a/scripts/csops/csi
+++ b/scripts/csops/csi
@@ -232,6 +232,17 @@ if [[ $rebuild_services_needed == true ]]; then
 	rm -r /tmp/cspace-bindings-*
 	rm -r /tmp/merged-app-config-*
 
+	if [[ -z $INSTALLED_VERSION ]]; then
+		# Import permissions on the initial install.
+
+		echo "Importing permissions..."
+
+		if ! ant import; then
+			echo "ERROR: Failed to import permissions"
+			exit 1
+		fi
+	fi
+
 	# A full deploy of the services layer deploys the ui and services artifacts,
 	# so set these to false.
 
